#List of affix configurations
[[affixes]]
  identifier = "champions:adaptable"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:arctic"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:dampening"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:desecrating"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:enkindling"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:hasty"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:infested"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:knocking"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:lively"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:magnetic"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:molten"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:paralyzing"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:plagued"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:reflective"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:shielding"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
#List of affix configurations
[[affixes]]
  identifier = "champions:wounding"
  enabled = true
  minTier = 1
  maxTier = 100
  mobList = []
  mobPermission = "BLACKLIST"
